### ISSUE TITLE
Preparar tutorial de Maven

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#1]
De acuerdo a la reunión del domingo 6 octubre Diego y Víctor se comprometen a realizar un tutorial para el uso y manejo de Maven,  para la siguiente reunión que se celebrará el 13 de octubre deberán mostrar los avances hasta el momento y como fecha final tendrán hasta el 20 de octubre.

**Comment by DiegoGonzalezPerez** [comment]
El domingo para la reunión de las 8 mostraremos los avances

**Comment by aadriii03** [comment]
50% del tutorial completado. En la reunión del 13 de octubre se comprometen a acabarlo para el 20 de octubre.

**Comment by DiegoGonzalezPerez** [comment]
Ya esta hecho y agregado el tutorial de maven para que lo podáis ver , si hay alguna pregunta lo comentaremos en la próxima reunión
