### ISSUE TITLE
Pruebas del código de la it.2

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#15]
Se espera poner a prueba el código generado en la implementación para los casos de uso requeridos para la iteración 2 y que se realice un informe de dichas pruebas y los resultados.

**Comment by DiegoGonzalezPerez** [comment]
Okey vamos a empezar las pruebas y ha redactar el documento aproximadamente en 2 horas te informare .

**Comment by vict0r123** [comment]
Terminadas las pruebas de la it2 af8cce99183076816f4df5f12d36b54170bcb934
