### ISSUE TITLE
Comienzo de requisitos de la Iteración 1 

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#2]
Tal y como dice la planificación del proyecto comenzamos a definir los requisitos correspondientes a la iteración 1, para hoy deberán estar acabados y pasar al análisis.

**Comment by SergioCarmonaPovedano** [comment]
Adjunto el archivo con los requisitos definidos:

[Documento_Requisitos_Iteracion1.pdf](https://github.com/user-attachments/files/17546325/Documento_Requisitos_Iteracion1.pdf)

**Comment by SergioCarmonaPovedano** [comment]
Adjuntado ya que el archivo con los requisitos definidos (iteración 1).

https://github.com/aadriii03/-ISO24-ISO2-B04/blob/752cae228095b377dc286d629f58a485a11877b9/Documento_Requisitos_Iteracion1.pdf
