### ISSUE TITLE
Análisis It.4

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#24]
La abro hoy para empezar con análisis de la iteración cuatro, pero se tiene hasta mañana según la planificación.

**Comment by SergioCarmonaPovedano** [comment]
Adjunto el documento correspondiente a la fase de análisis de la iteración 4:
https://github.com/aadriii03/-ISO24-ISO2-B04/blob/72a27c2431e5c8bd37568698272187fb19b2a083/Documento_Analisis_Iteracion_4.pdf
