### ISSUE TITLE
Realizar el analisis correspondiente a la Iteración 1

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#3]
De acuerdo con la planificacion una vez acabados los requisitos, pasareis a realizar el analisis de la iteracion 1.

**Comment by SergioCarmonaPovedano** [comment]
https://github.com/aadriii03/-ISO24-ISO2-B04/blob/7b728d4ac20b0d72c348171045599c8042ca1aeb/Analisis%20iteracci%C3%B3n1.pdf
