### ISSUE TITLE
Diseño de los casos de uso It.1 

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#4]
Deberéis de comenzar con el diseño de los casos de uso correspondientes a la iteración 1, tal y como marca la planificación.
Tras acabarlo subir los archivos .vpp al repositorio en su rama correspondiente.

**Comment by aadriii03** [comment]
Perfecto únicamente queda un caso de uso y podemos seguir con implementación.
 Gracias.

**Comment by lauradiazmondejar** [comment]
Subido el diagrama de casos de uso 11 
https://github.com/aadriii03/-ISO24-ISO2-B04/commit/6ee9086fb124b558ccb7e8c9ace32c93c117a9e2
Con esto daríamos por finalizada la fase de diseño
