### ISSUE TITLE
Análisis It.7

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#59]
Comenzamos la fase de análisis de la ultima iteración.

**Comment by SergioCarmonaPovedano** [comment]
Adjunto documentos (formato .vpp) correspondientes a la fase de análisis de la iteración 7.
https://github.com/aadriii03/-ISO24-ISO2-B04/blob/c91a56f11eaad348edd61d2ee0ed4cd16d288ff1/Analisis_CDU12_It.7.vpp
https://github.com/aadriii03/-ISO24-ISO2-B04/blob/c91a56f11eaad348edd61d2ee0ed4cd16d288ff1/Analisis(Estatico)_CDU12_It.7.vpp
