### ISSUE TITLE
Realizar pruebas It.1

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#6]
Solo queda realizar pruebas de la implementación para finalizar la iteración 1.

**Comment by DiegoGonzalezPerez** [comment]
Perfecto mañana sobre las 10 Victor y yo comenzaremos las pruebas para la Iteracion 1 .

**Comment by vict0r123** [comment]
Fase de pruebas acabada
https://github.com/aadriii03/-ISO24-ISO2-B04/commit/e025de488ef0788b0c1a328e4290fc95651ae8f9
