### ISSUE TITLE
It1 - Servidor - Requisitos 

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#74]
Tal y como se acordó en la reunión del 17 de noviembre, se hizo la estructura de cliente servidor y comienza hoy con la primera iteracion del servidor definiendo los requisitos.

**Comment by SergioCarmonaPovedano** [comment]
Terminada la fase de requisitos correspondiente a la it.1 (servidor).
Adjunto enlace del commit correspondiente al archivo .vpp: https://github.com/aadriii03/-ISO24-ISO2-B04/blob/777db5d5c4ce6f75e7ffaf5d3fd86918a6a72bb4/Servidor-B04-ISOII.vpp
