### ISSUE TITLE
It1 - Servidor - Analisis

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#76]
Una vez finalizada la definición de los requisitos y los casos de uso de la iteración 1 del servidor procedemos al análisis.

**Comment by SergioCarmonaPovedano** [comment]
Terminada la fase de análisis correspondiente a la it.1
Adjunto el enlace del commit del documento .vpp: https://github.com/aadriii03/-ISO24-ISO2-B04/blob/08af95620c58356c85234d0ccc00f94c35fa75f9/Servidor-B04-ISOII.vpp
