### ISSUE TITLE
It1 - Servidor - Diseño

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#78]
Dejo hoy ya abierto el issue de diseño correspondiente a la iteración 1 del servidor, puesto que comenzara mañana y se deberá subir el diagrama de clases correspondiente.

**Comment by lauradiazmondejar** [comment]
Subido el diagrama de clases de diseño perteneciente a la iteración 1. Con esto daríamos por finalizada la fase de diseño. c740397
