### ISSUE TITLE
Análisis de requisitos y casos de uso IT.2

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#8]
Documentación del resultado del análisis de los requisitos y casos de uso involucrados en la iteración 2.

**Comment by SergioCarmonaPovedano** [comment]
https://github.com/aadriii03/-ISO24-ISO2-B04/blob/2aa13e09d1d0baf8073fe938ac24339ce8297377/Documento%20de%20An%C3%A1lisis%20IT.2.pdf
