### ISSUE TITLE
Diseño de los casos de uso de la IT.2

### ISSUE THREAD

**Issue by aadriii03** [aadriii03/-ISO24-ISO2-B04#9]
Crear el diseño de los casos de uso involucrados en esta iteración.

**Comment by lauradiazmondejar** [comment]
Subidos los diagramas de los casos de uso 4 y 6 (8847acb)

**Comment by JeronimodlaCruz** [comment]
Subido el diagrama del caso de uso 10. Con esto finaliza la fase de diseño (https://github.com/aadriii03/-ISO24-ISO2-B04/commit/87ed5c000648a8f49434894ef01ff953809e77f3)
